import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/globals/header";
import { Nunito_Sans } from "next/font/google";

const NunitoSans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "AVO - UI UX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NunitoSans.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
